BrnoMVC1.Web/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrnoMVC1.Web.Controllers
{
    public class HelloWorldController : Controller
    {
       

        // GET: HelloWorld
        public ActionResult Index()
        {
            string text = "Hello World 2";
            
            return View(model: text);
        }
    }
}

BrnoMVC1.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hello World", "Index", "HelloWorld")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                    <li>@Html.ActionLink("User", "Index", new { Area = "Administration", Controller = "User", Test = "Ahoj", Test2 = 5 }, null)</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@

            </div>
            @Html.Partial("_MyLoginPartial")
        </div>
    </div>
    <div class="container body-content">
        <br /><br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/application")

    @RenderSection("scripts", required: false)
</body>
</html>

BrnoMVC1.Web/Views/Shared/_MyLoginPartial.cshtml
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p>MOJE PARTIAL LAYOUT</p>
        </li>
        <li>
    </ul>
    